# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Profile
    url: /
    weight: 10
  - name: Research
    url: projects/
    weight: 20
  - name: Publication
    url: /publication
    weight: 30
  - name: Teaching
    url: /teaching
    weight: 40
  - name: Talks
    url: /event
    weight: 50
  - name: Alumni
    url: alumni/
    weight: 60
  - name: Uses
    url: uses/
    weight: 40
